/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.telas;

import backend.BancoDeDados;
import backend.Carrinho;
import backend.Vendas;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author jonny
 */
public class ProdutosCliente extends javax.swing.JFrame {

    
    static BancoDeDados bancoDeDados;
    /**
     * Creates new form Produtos
     */
    public ProdutosCliente(BancoDeDados banco) {
        initComponents();
        
        this.bancoDeDados = banco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmbCategorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCarrinho = new javax.swing.JTextArea();
        txtEscolheProd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSelecionaCod = new javax.swing.JTextField();
        txtSelecionaQuant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcodigoIdentificacao = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCatSelecionada1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Top-guns");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cliente");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pistola", "Rifle", "Submetralhadora", "Pesada", "Branca" }));
        cmbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriasActionPerformed(evt);
            }
        });

        txtCarrinho.setColumns(20);
        txtCarrinho.setRows(5);
        jScrollPane1.setViewportView(txtCarrinho);

        txtEscolheProd.setText("Comprar");
        txtEscolheProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEscolheProdActionPerformed(evt);
            }
        });

        jLabel4.setText("Categorias");

        jLabel5.setText("Codigo do Produto");

        jLabel6.setText("Quantidade do Produto");

        txtSelecionaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelecionaCodActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo Identificacao");

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtCatSelecionada1.setColumns(20);
        txtCatSelecionada1.setRows(5);
        jScrollPane2.setViewportView(txtCatSelecionada1);

        jButton3.setText("Vendas já efetuadas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(23, 23, 23))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtcodigoIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSelecionaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSelecionaQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEscolheProd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelecionaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSelecionaQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigoIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addComponent(txtEscolheProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginCliente login = new LoginCliente(bancoDeDados);
        login.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSelecionaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelecionaCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelecionaCodActionPerformed

    private void cmbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriasActionPerformed
        // TODO add your handling code here:
        
        txtCatSelecionada1.setText("");
        
        String categoriaSelecionada = cmbCategorias.getSelectedItem().toString();
        String armazenaProdutos = null;
        
        for(int i = 0; i < bancoDeDados.produtos.size(); i++){
        if(categoriaSelecionada.equals(bancoDeDados.produtos.get(i).getCategoria()) && bancoDeDados.produtos.get(i).getQuantEstoque() > 0){
        
            armazenaProdutos = ("CATEGORIA: " + bancoDeDados.produtos.get(i).getCategoria() + "\n" +
                    "Nome: " + bancoDeDados.produtos.get(i).getNome() + " | Codigo: " + bancoDeDados.produtos.get(i).getCodigo() + " | Estoque: " 
                    + bancoDeDados.produtos.get(i).getQuantEstoque() + " | Preco: " + bancoDeDados.produtos.get(i).getPreco() + " R$\n" 
                    + "--------------------------------------------------------------------" + "\n");
            txtCatSelecionada1.append(armazenaProdutos);
            
    }//GEN-LAST:event_cmbCategoriasActionPerformed
        }
    }
    private void txtEscolheProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEscolheProdActionPerformed
        // TODO add your handling code here:
        
        int codSelecionado = 0;
        int quantSelecionada = 0;
        String codigoIdent;
        double resultado = 0;
        
        
        
        codigoIdent = txtcodigoIdentificacao.getText();
        codSelecionado = Integer.parseInt(txtSelecionaCod.getText());
        quantSelecionada = Integer.parseInt(txtSelecionaQuant.getText());
        
        for(int j = 0; j < bancoDeDados.clientes.size(); j++){
            
            if(bancoDeDados.clientes.get(j).getCodigoIdentificacao().equals(codigoIdent)){
                
                double compras = bancoDeDados.clientes.get(j).getCompras();
                
        for(int i = 0; i < bancoDeDados.produtos.size(); i++){
            
            if(codSelecionado == bancoDeDados.produtos.get(i).getCodigo()){
                
                compras = (bancoDeDados.produtos.get(i).getPreco() * quantSelecionada) + compras;
                
                bancoDeDados.clientes.get(j).setCompras(compras);
                
                 
               Carrinho carrinho = new Carrinho(bancoDeDados.produtos.get(i).getCategoria(),
                       bancoDeDados.produtos.get(i).getPreco() * quantSelecionada,
                       bancoDeDados.produtos.get(i).getNome(), bancoDeDados.produtos.get(i).getCodigo(), quantSelecionada, 
                       bancoDeDados.clientes.get(j).getNome(), bancoDeDados.clientes.get(j).getCodigoIdentificacao());
               bancoDeDados.addCarinho(carrinho);
               
            txtCarrinho.setText("");
               
            String impCarrinho;
            for(int u = 0; u < bancoDeDados.carrinho.size(); u++){
                
            impCarrinho = "CATEGORIA: " + bancoDeDados.carrinho.get(u).getCategoria() + "\n" +
                    "Nome: " + bancoDeDados.carrinho.get(u).getNome() + " | Codigo: " + bancoDeDados.produtos.get(u).getCodigo() + " | Quantidade: " 
                    + quantSelecionada + " | Preco: " + bancoDeDados.carrinho.get(u).getPreco() + " R$" + " | Total: " + compras + "\n"
                    + "-------------------------------------------------------------------------------------------------------------------------------" + "\n";
            txtCarrinho.append(impCarrinho);
            }
               
               
            }
        }
        
        resultado = compras;
        }
        }
       
        System.out.println(resultado);
        
    }//GEN-LAST:event_txtEscolheProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
         
        double verifica = 0;
        
        for(int i = 0; i < bancoDeDados.clientes.size();i++){
            if(bancoDeDados.clientes.get(i).getCodigoIdentificacao().equals(txtcodigoIdentificacao.getText())){
                for(int j = 0; j < bancoDeDados.carrinho.size(); j++){
            Vendas venda = new Vendas(bancoDeDados.carrinho.get(j).getCategoria(), 
                        bancoDeDados.carrinho.get(j).getPreco(), bancoDeDados.carrinho.get(j).getNome(), 
                        bancoDeDados.carrinho.get(j).getCodigo(), bancoDeDados.carrinho.get(j).getQuantEstoque(), 
                       bancoDeDados.clientes.get(i).getNome(), bancoDeDados.clientes.get(i).getCodigoIdentificacao());
            bancoDeDados.addVendas(venda);
            bancoDeDados.produtos.get(i).setQuantEstoque(bancoDeDados.produtos.get(i).getQuantEstoque() - bancoDeDados.carrinho.get(i).getQuantEstoque());
        }
                bancoDeDados.clientes.get(i).setCompras(0);
                verifica = bancoDeDados.clientes.get(i).getCompras();
            }
        }
        
        for(int i = 0; i < bancoDeDados.carrinho.size(); i++){
             bancoDeDados.carrinho.remove(i);
        }
        
        
        if(bancoDeDados.carrinho.isEmpty()){
            System.out.println("tudo feito");
        }
        
        JOptionPane.showMessageDialog(null, "Compra finalizada! " + verifica);
        
        txtCarrinho.setText("");
        txtSelecionaCod.setText("");
        txtSelecionaQuant.setText("");
        txtcodigoIdentificacao.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        VendasClientes vendasCli = new VendasClientes(bancoDeDados);
        
        vendasCli.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosCliente(bancoDeDados).setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCarrinho;
    private javax.swing.JTextArea txtCatSelecionada1;
    private javax.swing.JButton txtEscolheProd;
    private javax.swing.JTextField txtSelecionaCod;
    private javax.swing.JTextField txtSelecionaQuant;
    private javax.swing.JTextField txtcodigoIdentificacao;
    // End of variables declaration//GEN-END:variables
}
